# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.8.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.8.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/masa/git/C-practice

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/masa/git/C-practice

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.8.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.8.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/masa/git/C-practice/CMakeFiles /Users/masa/git/C-practice/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/masa/git/C-practice/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named target/lesson1

# Build rule for target.
target/lesson1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 target/lesson1
.PHONY : target/lesson1

# fast build rule for target.
target/lesson1/fast:
	$(MAKE) -f CMakeFiles/target/lesson1.dir/build.make CMakeFiles/target/lesson1.dir/build
.PHONY : target/lesson1/fast

src/calc.o: src/calc.c.o

.PHONY : src/calc.o

# target to build an object file
src/calc.c.o:
	$(MAKE) -f CMakeFiles/target/lesson1.dir/build.make CMakeFiles/target/lesson1.dir/src/calc.c.o
.PHONY : src/calc.c.o

src/calc.i: src/calc.c.i

.PHONY : src/calc.i

# target to preprocess a source file
src/calc.c.i:
	$(MAKE) -f CMakeFiles/target/lesson1.dir/build.make CMakeFiles/target/lesson1.dir/src/calc.c.i
.PHONY : src/calc.c.i

src/calc.s: src/calc.c.s

.PHONY : src/calc.s

# target to generate assembly for a file
src/calc.c.s:
	$(MAKE) -f CMakeFiles/target/lesson1.dir/build.make CMakeFiles/target/lesson1.dir/src/calc.c.s
.PHONY : src/calc.c.s

src/main1.o: src/main1.c.o

.PHONY : src/main1.o

# target to build an object file
src/main1.c.o:
	$(MAKE) -f CMakeFiles/target/lesson1.dir/build.make CMakeFiles/target/lesson1.dir/src/main1.c.o
.PHONY : src/main1.c.o

src/main1.i: src/main1.c.i

.PHONY : src/main1.i

# target to preprocess a source file
src/main1.c.i:
	$(MAKE) -f CMakeFiles/target/lesson1.dir/build.make CMakeFiles/target/lesson1.dir/src/main1.c.i
.PHONY : src/main1.c.i

src/main1.s: src/main1.c.s

.PHONY : src/main1.s

# target to generate assembly for a file
src/main1.c.s:
	$(MAKE) -f CMakeFiles/target/lesson1.dir/build.make CMakeFiles/target/lesson1.dir/src/main1.c.s
.PHONY : src/main1.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... target/lesson1"
	@echo "... src/calc.o"
	@echo "... src/calc.i"
	@echo "... src/calc.s"
	@echo "... src/main1.o"
	@echo "... src/main1.i"
	@echo "... src/main1.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

